# Generated by Django 3.2.7 on 2021-10-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click the above link..to read blog..', max_length=255),
        ),
    ]
